import { Module } from '@nestjs/common'
import { APP_GUARD } from '@nestjs/core'
import { ConfigModule } from '@nestjs/config'
import { PrismaService } from './prisma.service'
import { HealthModule } from './health/health.module'
import { AuthModule } from './auth/auth.module'
import { DevicesModule } from './devices/devices.module'
import { InterfacesModule } from './interfaces/interfaces.module'
import { ClientsModule } from './clients/clients.module'
import { AlertsModule } from './alerts/alerts.module'
import { UsersModule } from './users/users.module'
import { RolesModule } from './roles/roles.module'
import { DataModule } from './data/data.module'
import { IncidentsModule } from './incidents/incidents.module'
import { EventsModule } from './events/events.module'
import { SyslogModule } from './syslog/syslog.module'
import { SnmpModule } from './snmp/snmp.module'
import { NotificationsModule } from './notifications/notifications.module'
import { WhatsappModule } from './whatsapp/whatsapp.module'
import { RecipientsModule } from './recipients/recipients.module'
import { NocModule } from './noc/noc.module'
import { AuditModule } from './audit/audit.module'
import { JwtAuthGuard } from './auth/jwt-auth.guard'

@Module({ imports: [ConfigModule.forRoot({ isGlobal: true }), HealthModule, AuthModule, DevicesModule, InterfacesModule, ClientsModule, AlertsModule, UsersModule, RolesModule, IncidentsModule, EventsModule, SyslogModule, SnmpModule, NotificationsModule, WhatsappModule, RecipientsModule, NocModule, AuditModule, DataModule], providers: [PrismaService, { provide: APP_GUARD, useClass: JwtAuthGuard }], exports: [PrismaService] })
export class AppModule {}
