import { useState } from 'react'
import type { FormEvent } from 'react'
import './theme-overrides.css'

type Device = { name: string; ip: string; vendor: string; model: string; type: string; location: string; snmp: string; status: string; lastSeen: string }
type Port = { port: string; client: string; speed: string; admin: string; operational: string }

const devices: Device[] = [
  { name: 'Core-SW-01', ip: '10.10.10.1', vendor: 'Cisco', model: 'C9300-48P', type: 'Switch', location: 'Main POP', snmp: 'v2c', status: 'Online', lastSeen: 'Just now' },
  { name: 'Core-SW-02', ip: '10.10.10.5', vendor: 'Huawei', model: 'S5720-52X', type: 'Switch', location: 'Main POP', snmp: 'v2c', status: 'Online', lastSeen: '1 min ago' },
  { name: 'Access-SW-01', ip: '10.10.20.1', vendor: 'Cisco', model: 'C2960X-48', type: 'Switch', location: 'North Hub', snmp: 'v2c', status: 'Online', lastSeen: '2 min ago' },
  { name: 'Access-SW-02', ip: '10.10.10.2', vendor: 'MikroTik', model: 'CRS326-24G', type: 'Switch', location: 'East Hub', snmp: 'v2c', status: 'Online', lastSeen: '1 min ago' },
  { name: 'Access-SW-03', ip: '10.10.10.3', vendor: 'Cisco', model: 'C2960X-48', type: 'Switch', location: 'West Hub', snmp: 'v2c', status: 'Offline', lastSeen: '18 min ago' },
  { name: 'Edge-Router-01', ip: '10.10.10.254', vendor: 'MikroTik', model: 'CCR2004', type: 'Router', location: 'Main POP', snmp: 'v2c', status: 'Online', lastSeen: 'Just now' },
]
const ports: Record<string, Port[]> = {
  'Core-SW-01': [{ port: 'Gi0/1', client: 'Core uplink', speed: '1G', admin: 'UP', operational: 'UP' }, { port: 'Gi0/24', client: 'Distribution uplink', speed: '1G', admin: 'UP', operational: 'UP' }],
  'Core-SW-02': [{ port: 'GE0/0/1', client: 'Core uplink', speed: '10G', admin: 'UP', operational: 'UP' }, { port: 'GE0/0/48', client: 'Management', speed: '1G', admin: 'UP', operational: 'UP' }],
  'Access-SW-01': [{ port: 'Gi0/1', client: 'North uplink', speed: '1G', admin: 'UP', operational: 'UP' }, { port: 'Gi0/12', client: 'City School', speed: '1G', admin: 'UP', operational: 'UP' }],
  'Access-SW-02': [{ port: 'Gi0/1', client: 'East uplink', speed: '1G', admin: 'UP', operational: 'UP' }, { port: 'Gi0/8', client: 'XYZ Traders', speed: '1G', admin: 'UP', operational: 'UP' }, { port: 'Gi0/12', client: 'ABC Telecom', speed: '1G', admin: 'UP', operational: 'DOWN' }],
  'Access-SW-03': [{ port: 'Gi0/1', client: 'West uplink', speed: '1G', admin: 'UP', operational: 'DOWN' }, { port: 'Gi0/20', client: 'Mega Store', speed: '1G', admin: 'UP', operational: 'DOWN' }],
  'Edge-Router-01': [{ port: 'ether1', client: 'Core uplink', speed: '10G', admin: 'UP', operational: 'UP' }, { port: 'ether8', client: 'NOC management', speed: '1G', admin: 'UP', operational: 'UP' }],
}
function Status({ value }: { value: string }) { return <span className={`status ${value.toLowerCase()}`}><i />{value}</span> }
function Login({ onLogin }: { onLogin: () => void }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); if (username && password) onLogin(); else setError('Enter your username and password') }; return <main className="login-page"><section className="login-brand"><img src="/kkn-logo.svg" alt="KKN" /><p>Monitoring System</p></section><form className="login-card" onSubmit={submit}><h1>Sign in</h1>{error && <p className="login-error">{error}</p>}<label>Username<input value={username} onChange={event => setUsername(event.target.value)} autoComplete="username" required /></label><label>Password<input value={password} onChange={event => setPassword(event.target.value)} type="password" autoComplete="current-password" required /></label><button className="login-submit" type="submit">Login</button></form></main> }
function Devices() { const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Device | null>(null); const shown = devices.filter(device => `${device.name} ${device.ip} ${device.vendor} ${device.model}`.toLowerCase().includes(query.toLowerCase())); return <main className="device-app"><header className="device-header"><div className="app-mark"><img src="/kkn-logo.svg" alt="KKN" /></div><div><small>MONITORING SYSTEM</small><h1>Devices</h1></div><div className="header-state"><i /> System operational</div></header><section className="device-content"><div className="page-intro"><div><span className="eyebrow">NETWORK INVENTORY</span><h2>Device status</h2><p>All equipment, ports, clients, and operational state in one view.</p></div><strong>{shown.length} devices</strong></div><div className="device-toolbar"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search device, IP, vendor, or model" /><span>Online <b>{devices.filter(device => device.status === 'Online').length}</b></span><span>Offline <b>{devices.filter(device => device.status === 'Offline').length}</b></span></div><div className="device-table-wrap"><table><thead><tr><th>Device</th><th>IP address</th><th>Vendor / model</th><th>Type</th><th>Location</th><th>Ports</th><th>SNMP</th><th>Status</th><th /></tr></thead><tbody>{shown.map(device => { const devicePorts = ports[device.name] ?? []; const down = devicePorts.filter(port => port.operational === 'DOWN').length; return <tr key={device.name}><td><b>{device.name}</b><small>Last seen {device.lastSeen}</small></td><td><code>{device.ip}</code></td><td>{device.vendor}<small>{device.model}</small></td><td>{device.type}</td><td>{device.location}</td><td><b>{devicePorts.length}</b><small className={down ? 'down-text' : ''}>{down ? `${down} down` : 'All up'}</small></td><td><span className="tag">{device.snmp}</span></td><td><Status value={device.status} /></td><td><button className="details-button" onClick={() => setSelected(device)}>View details</button></td></tr> })}</tbody></table></div></section>{selected && <DeviceDetails device={selected} onClose={() => setSelected(null)} />}</main> }
function DeviceDetails({ device, onClose }: { device: Device; onClose: () => void }) { const devicePorts = ports[device.name] ?? []; return <div className="modal-backdrop" onMouseDown={onClose}><section className="device-modal" onMouseDown={event => event.stopPropagation()}><header><div><span className="eyebrow">DEVICE DETAILS</span><h2>{device.name}</h2></div><button className="close-button" onClick={onClose}>Close</button></header><div className="detail-grid">{[['IP address', device.ip], ['Vendor', device.vendor], ['Model', device.model], ['Type', device.type], ['Location', device.location], ['SNMP version', device.snmp], ['Last seen', device.lastSeen], ['Device status', device.status]].map(([label, value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div><div className="port-heading"><div><h3>Ports and connected clients</h3><p>Administrative, speed, operational, and alert state</p></div><span>{devicePorts.filter(port => port.operational === 'UP').length} up / {devicePorts.filter(port => port.operational === 'DOWN').length} down</span></div><div className="port-table-wrap"><table><thead><tr><th>Port</th><th>Client / description</th><th>Speed</th><th>Admin</th><th>Operational</th></tr></thead><tbody>{devicePorts.map(port => <tr key={port.port}><td><code>{port.port}</code></td><td><b>{port.client}</b></td><td>{port.speed}</td><td><Status value={port.admin} /></td><td><Status value={port.operational} /></td></tr>)}</tbody></table></div></section></div> }
export default function App() { const [loggedIn, setLoggedIn] = useState(false); return loggedIn ? <Devices /> : <Login onLogin={() => setLoggedIn(true)} /> }
